services:
  postgres:
    image: postgres:16.1
    environment:
      POSTGRES_USER: ${REALEST_POSTGRES_USER:-realest}
      POSTGRES_PASSWORD: ${REALEST_POSTGRES_PASSWORD:-realest_password}
      POSTGRES_DB: ${REALEST_POSTGRES_DB:-realestDb}
    networks:
      - realest-network
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  realest_site:
    build:
      context: ./realest_site
    environment: 
      POSTGRES_USER: ${REALEST_POSTGRES_USER:-realest}
      POSTGRES_PASSWORD: ${REALEST_POSTGRES_PASSWORD:-realest_password}
      POSTGRES_DB: ${REALEST_POSTGRES_DB:-realestDb}
      POSTGRES_HOST: ${REALEST_POSTGRES_HOST:-realest-postgres-1}
    expose:
      - 8000
    networks:
      - realest-network
    depends_on:
      - postgres

  realest_scrap:
    build:
      context: ./realest_scrap
    environment: 
      POSTGRES_USER: ${REALEST_POSTGRES_USER:-realest}
      POSTGRES_PASSWORD: ${REALEST_POSTGRES_PASSWORD:-realest_password}
      POSTGRES_DB: ${REALEST_POSTGRES_DB:-realestDb}
      POSTGRES_HOST: ${REALEST_POSTGRES_HOST:-realest-postgres-1}
    expose:
      - 6800
    networks:
      - realest-network
    depends_on:
      - postgres

  web-server:
    build:
      context: ./nginx_setup
    ports:
      - 8080:8080
    depends_on:
      - realest_site
    networks:
      - realest-network

networks:
  realest-network:
    driver: bridge
    name: realest-network

volumes:
  postgres_data:
